### ISSUE TITLE
Warning - content ID received with no value

### ISSUE THREAD

**Issue by agenciaregex** [tiktok/gtm-template-pixel#1]
Hi everyone!
Using this template, I tryed to set the viewcontent event:
![Print_ 2022 11 17_12](https://user-images.githubusercontent.com/118448645/202450539-6c22c896-00f0-4bfa-b786-eaf355c4f7fc.jpg)

But I am receiving warning that the content ID received has no value:
![Print_ 2022 11 17_13](https://user-images.githubusercontent.com/118448645/202450745-05453c6d-0c3d-43dd-a1bf-913c4a29cd4d.jpg)

Details of the configuration tag:
![Print_ 2022 11 17_14](https://user-images.githubusercontent.com/118448645/202450892-7e67e627-6ec1-485a-83c5-666433e1d726.jpg)

**func - get products - viewcontent TikTok**
`function(){

  var variants = {{JS - LS.variants}};
  var product = {};
  
  if (variants.length > 0){   
    
    var products = [];  

    for (i=0;i<variants.length;i++){
        product= {
          content_id: variants[i].id,
          content_type: 'product',
	      content_name: {{JS - LS.product.name}},
	      price: variants[i].price_number,
        };
        products.push(product);
    }
    return products;
  }
}
`

Someone know how to solve this issue?
Best regards,
Samuel.

**Comment by shiwei-tiktok** [comment]
Hi Samuel, 

To help us replicate this issue - could you share 2 things.

1. The JSON Data Layer structure of {{JS - LS.variants}} and
2. What data layer option are you using?

Best.
Shi Wei

**Comment by agenciaregex** [comment]
Shi Wei, ni hao ma?

For sure. I am sending the information requested.

1. Follow the variable:
![Print_ 2022 11 18_01](https://user-images.githubusercontent.com/118448645/202611593-9756d9fc-59ab-4617-93b6-5de551a0a7cc.jpg)

and the structure (if you prefer, can check more detais on your PC https://lojaregex.lojavirtualnuvem.com.br/):
![image](https://user-images.githubusercontent.com/118448645/202611864-15b1f931-0a4d-436e-9567-62e852106576.png)

![image](https://user-images.githubusercontent.com/118448645/202611753-e8d082b9-7eef-4bc9-bc9e-0b9dffb489f9.png)

2. LS.variants

The point is that: if I use the HTML structure on GTM to build the viewcontent event, it shows all the parameters with no error (including content ID). But when I use the GTM TikTok template, appear such error. Even using the same variable/function (func - get products - viewcontent TikTok).

If need any other information, don't hesitate to contact me.

Regards,
Samuel.

**Comment by eddie-tiktok** [comment]
Hi @agenciaregex , we pushed a fix. Can you try the latest template?

**Comment by agenciaregex** [comment]
Hi @eddie-tiktok, now the problem was solved. Thank you!
Regards,
Samuel.
