### ISSUE TITLE
Please I am waiting

### ISSUE THREAD

**Issue by SKR2004** [tiktok/gtm-template-pixel#3]
Please I am waiting
This problem worried me
Please help me as soon as possible
![image](https://user-images.githubusercontent.com/99620052/220073735-e82d0d1a-89bd-43ec-bb4f-e551b17dfd3b.png)

**Comment by eddie-tiktok** [comment]
Let's follow up on this in https://github.com/tiktok/gtm-template-pixel/issues/2
