### ISSUE TITLE
X NO_PERMISSION During Pixel Creation

### ISSUE THREAD

**Issue by DiscoverHolland** [tiktok/gtm-template-pixel#5]
While trying to attach a TikTok pixel to our google tags , we receive the error code "NO_PERIMSSION" which is not a code that is described on the business center help desk page - I understand what it means, but what can I do to fix this?

Thank you!

**Comment by eddie-tiktok** [comment]
@DiscoverHolland Could you walk me through how you arrived at this error?

**Comment by DiscoverHolland** [comment]
Hi,

I made my video in the creator by having the app connected to my phones photos / videos, and once I was done creating my video, I went to record the audio. I recorded the audio bit by bit, purposefully leaving breaks in-between some sentences, and went to play it back. The playback did not include my purposeful breaks, and it cut the end of each sentence with the start of the next one. The record button would acknowledge my breaks with a small caption saying "you can't record over current audio".

I ended up making the video and recording the audio in another app, and then just adding music to it in TikTok.

I tried a few different times to record, after closing out of the app, restarting my phone, uninstalling and reinstalling and so forth -Nothing has fixed this glitch.

Let me know what else you need to help diagnose.

Jessi McKim
Social Media Manager
***@***.******@***.***>
616.394.0000

Holland Area Convention
 & Visitors Bureau
78 East 8th Street
Holland, MI 49423
www.holland.org<https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.holland.org%2F&data=05%7C01%7Cjessi%40holland.org%7C78871ff57c024c6fea4e08da8b6484d3%7C807c1fb85c1546eca4cf9cd5c0dd77ac%7C1%7C0%7C637975561105984778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7vysMgUYzIrFsf5DmZFlug6824GaKDwGcI3zA2qqOvQ%3D&reserved=0>

**Comment by eddie-tiktok** [comment]
Hi there, sorry we're not able to help you with in-app related issues. We're only the maintainers of this repo, the Google Tag Manager template. Maybe you can try reaching out on the app itself, or through [TikTok for Business](https://www.tiktok.com/business).
