### ISSUE TITLE
Enhanced Ecommerce with Google Analytics 4

### ISSUE THREAD

**Issue by steliosCha** [tiktok/gtm-template-pixel#6]
Will you set up the enhanced ecommerce option to work with google analytics 4 datalayer structure?

**Comment by shiwei-tiktok** [comment]
Hey @steliosCha 

If you are referring to https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtm, we do support the Data Layer structure. When using the template, follow these steps:

1. Under Object Properties "Use Google Analytics E-commerce Data Layers"
2. Select "Standard Ecommerce"

Our template will then grab the relevant content data!

Cheers,
Shi Wei
