### ISSUE TITLE
Implementation Problems with Custom Events in Google Tag Manager 

### ISSUE THREAD

**Issue by Jokeulr** [tiktok/gtm-template-pixel#8]
I implemented the tiktok Pixel in GTM and tried to create custom events such as Lead & Booking Lead. The event fires and is getting recognized by tiktok but i can not select these events for optimization purposes in my campaign setup.

**Comment by hanzhangtt** [comment]
Hi, I am sorry for the problems you run into, but we are only the code maintainer of Google Tag Manager template itself. 
To get better support from our dedicated support team, please submit a ticket [here]( https://ads.tiktok.com/athena/requester/boards/1705151646989743?identify_key=6a1e079024806640c5e1e695d13db80949525168a052299b4970f9c99cb5ac78
)
