### ISSUE TITLE
Tiktok Pixel Helper does not detect my pixel

### ISSUE THREAD

**Issue by AntonioAbadWAM** [tiktok/gtm-template-pixel#9]
I installed my Tiktok pixel more than a month ago using Google Tag Manager on the web but the Pixel Helper doesn't pick it up although inside TIktok we can see that events are received. I've tried everything and it doesn't pick it up, why is that?

**Comment by hanzhangtt** [comment]
Hi, I am sorry for the problems you run into, but we are only the code maintainer of Google Tag Manager template itself.
To get better support from our dedicated support team, please submit a ticket [here](https://ads.tiktok.com/athena/requester/boards/1705151646989743?identify_key=6a1e079024806640c5e1e695d13db80949525168a052299b4970f9c99cb5ac78)
